[package]
name = "chip8-core"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = { workspace = true }
thiserror = { version = "1.0.60" }
tokio = { version = "1.37.0", features = ["rt"] }

p3-field = { workspace = true }
p3-uni-stark = { workspace = true }
p3-matrix = { workspace = true }
